# Generated by Django 3.0.8 on 2020-09-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_executivesstatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivesstatment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Executive'),
        ),
    ]
