# Generated by Django 3.0.8 on 2020-09-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200919_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('event_link_zoom', models.TextField(blank=True, null=True)),
                ('event_link_teams', models.TextField(blank=True, null=True)),
                ('event_link_web', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUser')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
        ),
    ]
