# Generated by Django 3.0.8 on 2020-09-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserClass'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role'),
        ),
    ]
