# Generated by Django 3.0.8 on 2020-09-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200919_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='category',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
