# Generated by Django 3.0.8 on 2020-09-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200919_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='role',
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('membership_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MembershipClass')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserClass')),
            ],
        ),
        migrations.AddField(
            model_name='accountuser',
            name='rmembership_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.MembershipRole'),
        ),
    ]
