# Generated by Django 3.0.8 on 2020-09-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200920_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprole',
            name='user_group',
        ),
        migrations.AlterField(
            model_name='executive',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MembershipRole'),
        ),
    ]
