# Generated by Django 3.0.8 on 2020-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200920_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='priority',
            field=models.CharField(blank=True, choices=[(1, '1'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), (7, '7')], default='Low', max_length=20, null=True),
        ),
    ]
