# Generated by Django 3.0.8 on 2020-09-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200920_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='valid_till_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
