# Generated by Django 3.0.8 on 2020-09-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20200911_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_text', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isHomeArticle', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUser')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
        ),
    ]
