# Generated by Django 3.0.8 on 2020-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepagetestimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagetestimonials',
            name='video',
        ),
        migrations.AddField(
            model_name='homepagetestimonials',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
