# Generated by Django 3.0.8 on 2020-09-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200920_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanners',
            name='tag_text_font_size',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanners',
            name='title_font_size',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
