# Generated by Django 3.0.8 on 2020-09-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mush_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
