# Generated by Django 3.0.8 on 2020-09-22 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_auto_20200922_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqueSellingPoint', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/vendor_images')),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('products', 'products'), ('services', 'services')], default='products', max_length=200, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUser')),
            ],
        ),
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/vendor_images')),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='TargetMarketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'target_markets_catories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTrading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phoneSales', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneCustomerQueries', models.CharField(blank=True, max_length=100, null=True)),
                ('emailSales', models.CharField(blank=True, max_length=100, null=True)),
                ('emilCustomerQueries', models.CharField(blank=True, max_length=100, null=True)),
                ('mainAddressCity', models.CharField(blank=True, max_length=100, null=True)),
                ('mainAddressResidence', models.CharField(blank=True, max_length=100, null=True)),
                ('mainAddressNeigbhourhood', models.CharField(blank=True, max_length=100, null=True)),
                ('zimraVendorID', models.CharField(blank=True, max_length=100, null=True)),
                ('taxClearance', models.FileField(blank=True, null=True, upload_to='media/vendor_images')),
                ('logoImage', models.ImageField(blank=True, null=True, upload_to='media/vendor_images')),
                ('time_update', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Business')),
            ],
            options={
                'verbose_name_plural': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TargetMarketCategory')),
            ],
            options={
                'verbose_name_plural': 'target_markets',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.TextField(blank=True, null=True)),
                ('old_price', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/vendor_images')),
                ('time', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_limits', models.IntegerField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('in_slider', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('virtual_products', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('shop_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Catergory')),
                ('targetMarket', models.ManyToManyField(to='products.TargetMarket')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='targetMarket',
            field=models.ManyToManyField(to='products.TargetMarket'),
        ),
        migrations.AddField(
            model_name='brand',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Vendor'),
        ),
    ]
